### ISSUE TITLE
Some objects in the GChat template in README doesn't work

### ISSUE THREAD

**Issue by Kotsuha** [1and1/go-gchat-notifier-plugin#33]
GoCD Version: 23.3.0 (16991-f38981e8aa684d63ac96f517996cd888eff37640).

Thanks for this plugin. I am trying it out. If I copy-paste the GChat template in README, there are errors.

![gocd-gchat-issue](https://github.com/1and1/go-gchat-notifier-plugin/assets/10438710/7cc9f948-188d-41cd-8e32-289ad041ea80)

It seems like the error is caused by `${serverInfo.secure_site_url}`.

![gocd-gchat-issue](https://github.com/1and1/go-gchat-notifier-plugin/assets/10438710/e02293a4-9932-430a-9fea-98755ae8b2f7)

**Comment by sfuhrm** [comment]
Thanks for the ticket! Probably some of the objects have changed in the meantime, so I'll need to consolidate.

**Comment by sfuhrm** [comment]
Just out of curiosity, do you access your GoCD via HTTP or HTTPS?

**Comment by sfuhrm** [comment]
I have tested with GoCD 23.4.0, it looks ok.

The serverInfo object comes from the server directly.
Please try the following and paste the results here:

GChat template:
```
<#list .serverInfo?keys as key>
  ${key}
</#list>
```

Condition for sending:
```
true
```

With this combination we'll get all keys of the serverInfo object with the next pipeline run.

**Comment by Kotsuha** [comment]
I cannot press the Apply button.

![Snipaste_2023-12-12_16-03-38](https://github.com/1and1/go-gchat-notifier-plugin/assets/10438710/73cf57d7-4249-4f95-8864-7c605692c79d)

Maybe I need to update my GoCD?

**Comment by Kotsuha** [comment]
I haven't update my GoCD yet. Still at GoCD Version: 23.3.0 (16991-f38981e8aa684d63ac96f517996cd888eff37640).

Thank you for guiding me with patience. There is no errors now, but my result is different. I only have `server_id`.

![gocd1](https://github.com/1and1/go-gchat-notifier-plugin/assets/10438710/d49983c9-4ed6-4dc8-a805-3ae828b18bab)
![gocd2](https://github.com/1and1/go-gchat-notifier-plugin/assets/10438710/93b6cc9e-abfa-4975-be60-be663329ab4b)

**Comment by sfuhrm** [comment]
Ok, then it is probably a bad idea to rely on `secure_site_url` when giving examples. It probably relies on certain server settings to be existing, and does not get transferred when they are missing.

I'll adapt the examples so the `secure_site_url` is optional and the template can live with that.

**Comment by sfuhrm** [comment]
@Kotsuha I have adjusted the README.
You can try it yourself:

```
*Failed:* ${stageStatus.pipeline.group}/${stageStatus.pipeline.name}/${stageStatus.pipeline.stage.name} is ${stageStatus.pipeline.stage.state}, result ${stageStatus.pipeline.stage.result}
<#list stageStatus.pipeline.stage.jobs as job>
${job.name}: ${job.result} <#if serverInfo['secure_site_url']??><${serverInfo.secure_site_url}/go/tab/build/detail/${stageStatus.pipeline.name}/${stageStatus.pipeline.counter}/${stageStatus.pipeline.stage.name}/${stageStatus.pipeline.stage.counter}/${job.name}|console></#if>
</#list>
```

This is the example that does graceful degradation when the `secure_site_url` is not set.

**Comment by Kotsuha** [comment]
> You can try it yourself:

No errors now. Thanks!
Should I close this one?

**Comment by sfuhrm** [comment]
Thanks for reporting
